# Generated by Django 4.2.2 on 2023-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_submissions_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='quiz.quiz'),
        ),
    ]
