# Generated by Django 4.2.2 on 2023-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_creator_alter_quiz_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(null=True),
        ),
    ]
