# Generated by Django 4.2.2 on 2023-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isFromApi',
            field=models.BooleanField(default=False),
        ),
    ]
